[project]
name = "firm"
version = "0.1.0"
description = "Filtered Inertial Rotation Module"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit"
]
