# Generate a Unity main() that RUN_TESTs every void test_*() in TEST_FILE.
# cmake -DTEST_FILE=... -DRUNNER_FILE=... -P generate_unity_runner.cmake

if(NOT TEST_FILE OR NOT RUNNER_FILE)
    message(FATAL_ERROR "TEST_FILE and RUNNER_FILE are required")
endif()

file(READ "${TEST_FILE}" contents)
string(REGEX MATCHALL "void[ \t]+test_[A-Za-z0-9_]+[ \t]*\\(" matches "${contents}")

if(NOT matches)
    message(FATAL_ERROR "No Unity test functions found in ${TEST_FILE}")
endif()

set(decls "")
set(runs "")
foreach(match IN LISTS matches)
    string(REGEX REPLACE "void[ \t]+(test_[A-Za-z0-9_]+)[ \t]*\\(" "\\1" name "${match}")
    string(APPEND decls "extern void ${name}(void);\n")
    string(APPEND runs "    RUN_TEST(${name});\n")
endforeach()

file(WRITE "${RUNNER_FILE}"
"/* Generated by generate_unity_runner.cmake. Do not edit. */
#include \"unity.h\"

extern void setUp(void);
extern void tearDown(void);
${decls}
int main(void)
{
    UNITY_BEGIN();
${runs}    return UNITY_END();
}
")
